FROM node:latest

# Inspired by Christian Lück <christian@lueck.tv> https://hub.docker.com/r/clue/adminer/~/dockerfile/
MAINTAINER Zeph Grunschlag <zgrunschlag@gmail.com>

ADD tzaffimssql /tzaffimssql
WORKDIR /tzaffimssql
RUN npm install

# Over-ride the default node command
CMD [ "/bin/bash" ]
